[workspace]

members = [
    "cl",
    "cli",
    "ffi",
    "rs-core",
    "rs-derive/*",
    "rs-extra",
    "rs-macro",
    "rs-proc-macro",
    "rs-wrapper-sys",
    "shared",
    "cool",
    "practice-multiple"
]
