/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface GlobalArrayAssigned {
  index: number
  size: bigint
}
export class OclBlock {
  constructor()
  initialize(): void
  enqueueBuffer(jsBuffer: Buffer): number
  dequeueBuffer(globalArrayIndex: number): Buffer
  getGlobalArrays(): Array<GlobalArrayAssigned>
}
