/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const DEFAULT_VECTOR_SIZE: number
export const DEFAULT_GLOBAL_ARRAY_COUNT: number
export function sum(a: number, b: number): number
export interface GlobalArrayAssigned {
  index: number
  size: bigint
}
export class OclBlock {
  constructor(vectorSize: number, globalArrayCount: number)
  initialize(): void
  enqueueBuffer(jsBuffer: Buffer): number
  dequeueBuffer(globalArrayIndex: number): Buffer
  getGlobalArrays(): Array<GlobalArrayAssigned>
}
