[package]
name = "rs-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "sum_macro"
path = "examples/sum_macro.rs"
