[package]
name = "rs-extra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-macro = { path = "../rs-macro", optional = true }
